const videos = [
  {
    id: '6Sfb-WU0Ir8',
    title: 'Joshua V Palmer',
    description: 'Meet Joshua V Palmer and learn about RC+.',
    credits: ['Directed by Joshua Rohde', 'Edited by RC+ Team'],
    directorNote: 'This project represents the beginning of something special. Thanks for watching!',
    thumbnail: 'https://img.youtube.com/vi/6Sfb-WU0Ir8/hqdefault.jpg',
  },
  {
    id: '-gNMU2gZ_iE',
    title: 'Interactive Interview',
    description: 'A short interactive film about a funeral home interview.',
    credits: ['Directed by Joshua Rohde', 'Edited by RC+ Team'],
    directorNote: 'This project represents the beginning of something special. Thanks for watching!',
    thumbnail: 'https://img.youtube.com/vi/-gNMU2gZ_iE/hqdefault.jpg',
  },
  {
    id: 'bUWVfUbXwlY',
    title: 'A For Anniversary',
    description: 'A heartfelt story about time and connection.',
    credits: ['Directed by Joshua Rohde', 'Edited by RC+ Team'],
    directorNote: 'This project represents the beginning of something special. Thanks for watching!',
    thumbnail: 'https://img.youtube.com/vi/bUWVfUbXwlY/hqdefault.jpg',
  },
  {
    id: '18QbgNnSjKk',
    title: 'Lucas Is Looking For Love',
    description: 'A chaotic and heartfelt pilot episode following Lucas as he navigates love, rejection, and some deeply questionable choices.',
    credits: ['Directed by Joshua Rohde', 'Edited by RC+ Team'],
    directorNote: 'This project represents the beginning of something special. Thanks for watching!',
    thumbnail: 'https://img.youtube.com/vi/18QbgNnSjKk/hqdefault.jpg',
  },
  {
    id: 'uiuruM6iyTU',
    title: 'Lucas Is Looking 2',
    description: 'In this sequel to the pilot, Lucas returns with even more awkward encounters, questionable fashion choices, and an unshakable determination to find love.',
    credits: ['Directed by Joshua Rohde', 'Edited by RC+ Team'],
    directorNote: 'This sequel builds off the original and dives deeper into Lucas’s lovable chaos. Thanks for watching!',
    thumbnail: 'https://img.youtube.com/vi/uiuruM6iyTU/hqdefault.jpg',
  },
  {
    id: 'zCMsRJuJBfQ',
    title: 'LILFL Concept Test 1',
    description: 'An early proof-of-concept for the Lucas Is Looking For Love series. This test explores tone, framing, and delivery for the character’s development.',
    credits: ['Created by Joshua Rohde', 'Starring Joshua Rohde'],
    directorNote: 'This was just a concept test, but it helped clarify the vibe and comedic rhythm I was aiming for. Thanks for checking it out.',
    thumbnail: 'https://img.youtube.com/vi/zCMsRJuJBfQ/hqdefault.jpg',
  },
  {
    id: 'RZTgEcLOgj0',
    title: 'Barking Dogs Seldom Bite',
    description: 'A dramatic short film about two girls who have gotten themselves way in over their heads. They reconnect and start to hash it out, while remembering the scars that brought them here.',
    credits: ['Written & Directed by Joshua Rohde', 'Starring Rene C. and [Add other actor’s name]'],
    directorNote: 'This one is heavy. It’s about friendships under pressure, memory, and the silent moments between the lines. I hope it hits home for someone.',
    thumbnail: 'https://img.youtube.com/vi/RZTgEcLOgj0/hqdefault.jpg',
  },
  {
    id: 'poBqBgz53EE',
    title: 'This Trail I Walk Again',
    description: 'An original country-inspired song by Joshua Rohde, reflecting on loss, change, and the resilience it takes to walk the same path again.',
    credits: ['Written & Performed by Joshua Rohde', 'Instrumental by Ryini Beats'],
    directorNote: 'This is one of the first songs I ever recorded. It’s raw, honest, and comes from a real place in my heart.',
    thumbnail: 'https://img.youtube.com/vi/poBqBgz53EE/hqdefault.jpg',
  },
  {
    id: 'dUnZWnDITUc',
    title: '[Promo 2] This Trail I Walk Again',
    description: 'A quick promo for Joshua Rohde’s original song, “This Trail I Walk Again.”',
    credits: ['Edited by Joshua Rohde'],
    directorNote: 'Just a short promo I made to build some hype around the release. Sometimes less is more.',
    thumbnail: 'https://img.youtube.com/vi/dUnZWnDITUc/hqdefault.jpg',
  },
  {
    id: 'X7WlDvxxgZ0',
    title: '[Promo 1] This Trail I Walk Again',
    description: 'A bold and gritty teaser for Joshua Rohde’s original song. A nosebleed, a monologue, and a tone that flips expectations.',
    credits: ['Written & Performed by Joshua Rohde'],
    directorNote: 'I wanted this promo to shock and amuse. It’s weird, raw, and unapologetically “me.”',
    thumbnail: 'https://img.youtube.com/vi/X7WlDvxxgZ0/hqdefault.jpg',
  },
  {
    id: 'kUhvES67V0k',
    title: '[LOST Promo] That Trail I Walk Again',
    description: 'The most intense and mysterious promo yet. Crumpled tissues, smeared red... is it blood? Is it paint? Is it genius? Probably.',
    credits: ['Created by Joshua Rohde'],
    directorNote: 'This was nearly forgotten. It’s gritty, strange, and has a totally different vibe — I love that.',
    thumbnail: 'https://img.youtube.com/vi/kUhvES67V0k/hqdefault.jpg',
  }  
];

export default videos;
